### ISSUE TITLE
Be able to provide the now value as a parameter to filter

### ISSUE THREAD

**Issue by gamebox** [wildlyinaccurate/angular-relative-date#15]
We often aren't very trusting of client side date calculations, what with the user being able to let their system clock get all sorts of out of sync with reality.  We also serve content that requires an exacting accuracy for legal reasons.  We'd like to be able to provide an override to the 'now' value as a parameter of the filter ie, `{{ someDate | relativeDate:serverTime }}` so that we can use our latest server timestamp to maintain accuracy within the level of granularity that is important to us and our users(usually no more than an hour).

I have a working patch, would you accept a PR?

**Comment by wildlyinaccurate** [comment]
Absolutely -- open up a PR and I'll take a look.

I'm guessing that simply using `.value('now' ...)` isn't suitable because the user's clock can change after that value is initialised?

**Comment by gamebox** [comment]
Well, we actually don't want to trust the user's clock at all.  With financial communications, you have to make sure that notices are based on accurate timestamps.  We've seen users browsing our site with clocks still set in 2009(this is in 2015).  `.value()` is nice but not usable when you want to have the value be dynamic

**Comment by gamebox** [comment]
Also, how are you running these tests?  I don't see a karma config file...

**Comment by wildlyinaccurate** [comment]
There's a `karma.conf.js` file in the root. Running the tests is a bit of a faff at the moment, it's on my to-do list to simplify it:

```
npm install
bower install
grunt build
```
