### ISSUE TITLE
null input ==> never ?

### ISSUE THREAD

**Issue by damiangreen** [wildlyinaccurate/angular-relative-date#22]
Is it possible to customer a response if the input is null?

I.e I have a login value and if it is null or empty string I wish to display 'never logged in'.
Currently It displays 'over a year ago'.

**Comment by wildlyinaccurate** [comment]
This behaviour is kind of inherent to the way that JavaScript deals with dates:

```
> new Date(null)
Thu Jan 01 1970 00:00:00 GMT+0000 (BST)
```

I would recommend handling the `null` case outside of this filter, e.g.

```html
<span ng-if="lastLoggedIn === null">Never logged in</span>
<span ng-if="lastLoggedIn !== null">{{ lastLoggedIn | relativeDate }}</span>
```
