### ISSUE TITLE
Relative day displayed as "Over a year from now" in Safari

### ISSUE THREAD

**Issue by trisle** [wildlyinaccurate/angular-relative-date#23]
It works perfectly fine on Chrome but not on Safari

`{{feed.created_at | relativeDate}}`

Chrome: 5 hours ago
Safari: Over a year from now

Might be related to this [SO question](http://stackoverflow.com/questions/25893148/angular-custom-filters-formatting-date-issue)?

**Comment by wildlyinaccurate** [comment]
Could you please provide an example value for `feed.created_at`?

**Comment by trisle** [comment]
It outputs a rather normal date string `2016-07-27 07:36:01`

I assume it's correct as both Chrome and Firefox shows the relative date just fine.

**Comment by wildlyinaccurate** [comment]
The `relativeDate` filter passes strings straight to the `new Date()` constructor, which is notoriously inconsistent across browsers. There are two ways to fix this:

 1. Use ISO 8601 strings e.g. `2016-07-27T07:36:01Z`
 2. Pass a `Date` object to `relativeDate`

**Comment by trisle** [comment]
Thanks for the reply. I actually did try passing in a Date object but wouldn't help.

**View**
`{{__date_obj(feed.created_at) | relativeDate}}`

**Controller**
``` javascript
$scope.__date_obj = function(date_str) {
	return new Date(date_str);
}
```
Still Chrome/Firefox works but not Safari :)

**Comment by wildlyinaccurate** [comment]
That has the exact same issue in that the `new Date(string)` constructor is inconsistent across browsers. If you are going to construct a Date object, you either need to use an ISO 8601 string or use the `new Date(year, month, day, hour, minutes, seconds)` form.
