### ISSUE TITLE
Please add a JSPM registry entry

### ISSUE THREAD

**Issue by skosarin** [wildlyinaccurate/angular-relative-date#24]
Currently, when running JSPM install, I have to specify to check npm for the package, by running `jspm install npm:angular-relative-date` but JSPM is unable to process some of the syntax in the npm registry, and thusly errors out.  Is it possible to add angular-relative-date to the JSPM registry?

**Comment by skosarin** [comment]
For reference:

> jspm install npm:angular-relative-date
>      Looking up npm:angular-relative-date
>      Updating registry cache...
>      Looking up npm:angular
>      Looking up npm:angular-translate
> ok   Installed npm:angular-translate@^2.11.0 (2.12.1)
> 
> err  Installing npm:angular-translate@2.12.1, no version match for npm:angular@~1.6.0
> 
> warn Installation changes not saved.

**Comment by wildlyinaccurate** [comment]
> no version match for npm:angular@~1.6.0

There's your problem: something is trying to install a version of Angular that doesn't exist in npm. 1.5.8 is the latest stable 1.x release. 1.6.0 is still in pre-release mode.

Regarding your request: I won't be supporting anything other than npm at this stage, sorry.
