### ISSUE TITLE
Incorrect dates in the future since 0.2.0

### ISSUE THREAD

**Issue by erdillon** [wildlyinaccurate/angular-relative-date#5]
Hi,

with 0.2.0, we're having issue because of dates like "8 min from now", where in fact it should be "just now".
This didn't occur with 0.1.1

It seems the "now" is set once only, upon first occurrence of the relativeDate filter. So, any use of that filter later on will show relative dates in the future from that moment.
We've reverted to using 0.1.1 for now.

**Comment by wildlyinaccurate** [comment]
Hi @erdillon, sorry for the unwanted behaviour - in retrospect, the addition of future dates should've warranted a major version bump.

I hadn't thought about the "now" thing, actually. It's really only there to make testing easier. Maybe this would be a good solution: by default, the value of "now" is `null`. Whenever the filter runs, it does something like `now = now || new Date()`. This way, I can still set the value of `now` in tests, but for "regular" usage, `now` will always be the current time.

Alternatively, I could add the option to disable future dates.

**Comment by erdillon** [comment]
Yeah. This seems like a good option that would work for us.

**Comment by deel77** [comment]
I have same problem with dates in future as "now" is populated only at the start of app. Can you correct it the way you describe. It would be better to use your original version from bower as I am using modified version, now. Thanks.

**Comment by wildlyinaccurate** [comment]
Sorry for the (long!) delay on this. I am running some tests with PR #7. If all goes well, I will merge it into master and tag v1.0.0.
