### ISSUE TITLE
Exaluate to add angular-relative to transifex and include translations into the package

### ISSUE THREAD

**Issue by evilaliv3** [wildlyinaccurate/angular-relative-date#8]
It would be valuable to evaluate to  add angular-relative to [transifex](https://www.transifex.com/) and include translations into the package.

This way the translatiion work would be done one shot for the project and then every project that will include the library will find the translations available.

Pushing the source strings and fetching them would be really simple; you find an example of how we do it in globaleaks on: https://github.com/globaleaks/GlobaLeaks/blob/master/client/Gruntfile.js

@EvanHahn, @siddii: it would be useful to collaborate eachother on this as some pieces of code may be relevant to would be valuable also for [HumanizeDuration](https://github.com/EvanHahn/HumanizeDuration.js) and [angular-timer](https://github.com/siddii/angular-timer)

\cc @mapmeld @fpietrosanti

**Comment by wildlyinaccurate** [comment]
Interesting suggestion, thanks. I'll look into Transifex at some point, but I currently have zero budget for my open-source projects so I don't think I'll be able to keep an active Transifex account.

**Comment by evilaliv3** [comment]
@wildlyinaccurate we can make it! transifex is also a free and volunteer  based community.

in addition we are part as the [open technology fund](https://www.opentechfund.org/) / [localization lab](http://www.localizationlab.org/) community and it would not be a problem to have some budget on having the library internationalized as part of the GlobaLeaks project.

**Comment by evilaliv3** [comment]
first of all before pushing the strings on transifex we have to be sure that this are really good in terms of source language and aim of the project.
let's review them together:

    just_now: 'just now',
    seconds_ago: '{{time}} seconds ago',
    a_minute_ago: 'a minute ago',
    minutes_ago: '{{time}} minutes ago',
    an_hour_ago: 'an hour ago',
    hours_ago: '{{time}} hours ago',
    a_day_ago: 'yesterday',
    days_ago: '{{time}} days ago',
    a_week_ago: 'a week ago',
    weeks_ago: '{{time}} weeks ago',
    a_month_ago: 'a month ago',
    months_ago: '{{time}} months ago',
    a_year_ago: 'a year ago',
    years_ago: '{{time}} years ago',
    over_a_year_ago: 'over a year ago',
    seconds_from_now: '{{time}} seconds from now',
    a_minute_from_now: 'a minute from now',
    minutes_from_now: '{{time}} minutes from now',
    an_hour_from_now: 'an hour from now',
    hours_from_now: '{{time}} hours from now',
    a_day_from_now: 'tomorrow',
    days_from_now: '{{time}} days from now',
    a_week_from_now: 'a week from now',
    weeks_from_now: '{{time}} weeks from now',
    a_month_from_now: 'a month from now',
    months_from_now: '{{time}} months from now',
    a_year_from_now: 'a year from now',
    years_from_now: '{{time}} years from now',
    over_a_year_from_now: 'over a year from now'

**Comment by wildlyinaccurate** [comment]
That would be awesome!

From my perspective, the strings which currently exist are fine. But I only use this component for very simple projects, so I'd be interested to hear your opinions on it.
